name: biblia_e_harpa
description: "Projeto voltado para desenvolvimento de biblia e harpa sem conexão com a internet"

publish_to: 'none'

version: 1.0.7+16

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  image_picker: ^0.8.7+3
  file_picker: any
  watcher: any
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: any
  just_audio: ^0.10.4
  just_audio_platform_interface: ^4.0.0
  dio: ^5.3.2
  cupertino_icons: ^1.0.8
  share_plus: ^11.0.0
  upgrader: ^8.4.0
  in_app_update: ^4.2.3
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/harpa_crista_640_hinos.json
    - assets/json/acf.json
    - assets/json/aa.json
    - assets/json/nvi.json
    - assets/json/devocional.json
    - assets/json/newDevocionalModel.json
    - assets/json/palavraDoDia.json
    - assets/json/apoio.json

flutter_icons:
  image_path: "assets/images/logoExecutavel.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#D3D3D3"
  adaptive_icon_foreground: "assets/images/logoExecutavel.png"