name: biblia_e_harpa
description: "Projeto voltado para desenvolvimento de bíblia e harpa sem conexão com a internet"
publish_to: 'none'
version: 1.1.3+23
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  file_picker: ^12.0.0-beta.5
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  just_audio: ^0.10.5
  just_audio_media_kit: ^2.1.0
  media_kit_libs_windows_audio: ^1.0.9
  dio: ^5.7.0
  cupertino_icons: ^1.0.8
  share_plus: ^13.1.0
  upgrader: ^13.5.0
  in_app_update: ^4.2.5
  url_launcher: ^6.3.0
  package_info_plus: ^10.1.0
  audio_service: ^0.18.12
  audio_session: ^0.2.3
  connectivity_plus: ^7.1.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.9.1
  provider: ^6.1.5+1
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/harpa_crista_640_hinos.json
    - assets/json/acf.json
    - assets/json/aa.json
    - assets/json/nvi.json
    - assets/json/newDevocionalModel.json
    - assets/json/palavraDoDia.json
    - assets/json/audios.json
    - assets/json/audiosHarpa.json
    - assets/json/quizz.json

flutter_icons:
  image_path: "assets/images/newLogoIcon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#D3D3D3"
  adaptive_icon_foreground: "assets/images/newLogoIcon.png"
