final List<String> harps = [
  "1 - Chuvas de Graça",
  "2 - Saudosa Lembrança",
  "3 - Plena Paz",
  "4 - Deus Velará Por Ti",
  "5 - Ó Desce Fogo Santo",
  "6 - Na Maldição Da Cruz",
  "7 - Cristo Cura Sim!",
  "8 - Cristo, O Fiel Amigo",
  "9 - Marchai Soldados De Cristo",
  "10 - Eu Te Louvo",
  "11 - Ó Cristão, Eia Avante",
  "12 - Vem Já, Pecador",
  "13 - Jesus Comprou-me",
  "14 - Gozo Em Jesus",
  "15 - Conversão",
  "16 - Despertar Para o Trabalho",
  "17 - Pensando Em Jesus",
  "18 - Grata Nova",
  "19 - O Convite De Cristo",
  "20 - Olhai o Cordeiro De Deus",
  "21 - Gloriosa Aurora",
  "22 - Ceia Do Senhor",
  "23 - Glória a Jesus",
  "24 - Poder Pentecostal",
  "25 - Jesus Tu és Bom",
  "26 - A Formosa Jerusálem",
  "27 - Amor Que Vence",
  "28 - Deus Vai Te Guiar",
  "29 - O Precioso Sangue",
  "30 - Não Sou Meu",
  "31 - Glória ao Meu Jesus",
  "32 - Meu Cristo! Meu Cristo!",
  "33 - Com Tua Mão Segura",
  "34 - Milícia De Jesus",
  "35 - O Grande Amor",
  "36 - O Exilado",
  "37 - Cristo Pra Mim",
  "38 - O Senhor é Rei",
  "39 - Alvo Mais Que a Neve",
  "40 - A Cidade Do Bom Jesus",
  "41 - A Cristo Coroai",
  "42 - Saudai Jesus",
  "43 - Doce Lar",
  "44 - Oh! Que Glória!",
  "45 - Redentor Onipotente",
  "46 - Um Pendão Real",
  "47 - Rocha Eterna",
  "48 - O Dia do Triunfo",
  "49 - Aleluia! Já Creio",
  "50 - Sempre Fiéis",
  "51 - Adoração Reconhecida",
  "52 - Tudo Está Bem",
  "53 - A Esperança da Igreja",
  "54 - Louvemos ao Redentor",
  "55 - Mais Perto da Tua Cruz",
  "56 - Tudo em Cristo",
  "57 - Vivifica-nos Senhor",
  "58 - Não Temas",
  "59 - Eu creio, Sim",
  "60 - Exultação do Crente",
  "61 - Deus Tomará Conta de Ti",
  "62 - Achei Jesus",
  "63 - Acordai, Acordai",
  "64 - De Todo o Mundo: Aleluia!",
  "65 - Quem Irá?",
  "66 - Pronto a Salvar",
  "67 - Quem Quer ir Com Cristo?",
  "68 - Gozo de Ter Salvação",
  "69 - Jesus Quebrou os Meus Grilhões",
  "70 - Cristo Vai Voltar",
  "71 - Santo és Tu, Senhor",
  "72 - Rasgou-se o Véu",
  "73 - Vem, Vem a Mim",
  "74 - Cristo Virá",
  "75 - Em Jesus Tens a Palma da Vitória",
  "76 - Vem, ó Pródigo",
  "77 - Guarda o Contacto",
  "78 - Meu Forte Redentor",
  "79 - Sua Graça Me Basta",
  "80 - Cristo Te Chama",
  "81 - Pode Salvar",
  "82 - Um Meigo Salvador",
  "83 - Não Posso Explicar",
  "84 - O Grande “Eu sou”",
  "85 - Deixai Entrar o Espírito de Deus",
  "86 - Satisfeito com Cristo",
  "87 - Meu Testemunho",
  "88 - Revela a Nós Senhor",
  "89 - Sublime e Grande Amor",
  "90 - Há Paz e Alegria",
  "91 - Nívea Luz",
  "92 - O Bondoso Salvador",
  "93 - Há Trabalho Pronto",
  "94 - Na Jerusalém de Deus",
  "95 - Ouve, ó Pecador",
  "96 - Deixa Penetrar a Luz",
  "97 - Há um Caminho Santo",
  "98 - Estarás Vigiando?",
  "99 - Eis o Dia a Declinar",
  "100 - O Bom Consolador",
  "101 - A Unção Real",
  "102 - Crê na Promessa",
  "103 - Caminhemos na Luz",
  "104 - Jesus Procura a Ovelha",
  "105 - A Gloriosa Esperança",
  "106 - Viva Cristo",
  "107 - Firme nas Promessas",
  "108 - Pelejar Por Jesus",
  "109 - Venha a Jesus",
  "110 - Clama: Jesus, Jesus!",
  "111 - Que Mudança!",
  "112 - O Nome Soberano",
  "113 - O Celeste Diretor",
  "114 - Aceita o Perdão de Jesus",
  "115 - Trabalhai e Orai",
  "116 - Livre Estou",
  "117 - O Senhor Salva a Todo o Pecador",
  "118 - Face a Face",
  "119 - Inesgotável é Seu Amor",
  "120 - Noite de Paz",
  "121 - Maravilhoso é Jesus",
  "122 - Fogo Divino",
  "123 - Cristo Voltará",
  "124 - Adoração",
  "125 - Quem Dera Hoje Vir!",
  "126 - Bem-Aventurança do Crente",
  "127 - O Senhor da Ceifa Chama",
  "128 - Entrega o Teu Coração",
  "129 - A Fonte Salvadora",
  "130 - Cristo é Meu!",
  "131 - De Valor Em Valor",
  "132 - Obreiros do Senhor",
  "133 - No Rol do livro",
  "134 - Jesus à Porta do Coração",
  "135 - O Nome Precioso",
  "136 - Jesus, Nosso Socorro",
  "137 - Liberto da Escravidão",
  "138 - Quem Bate é Jesus Cristo",
  "139 - Jesus, Meu Eterno Redentor",
  "140 - A Segurança do Crente",
  "141 - Guia-me Sempre, Meu Senhor",
  "142 - A Cidade Celeste",
  "143 - O Verdadeiro Amigo",
  "144 - Vem à Assembléia de Deus",
  "145 - União do Crente Com Seu Senhor",
  "146 - Caminho brilhante",
  "147 - Servir a Jesus",
  "148 - Bendirei a Jesus",
  "149 - Canto do Pescador",
  "150 - Para Casamentos",
  "151 - Fala Jesus Querido",
  "152 - Pela Cruz ao Céu Irei",
  "153 - Soldados de Cristo",
  "154 - Doce Nome de Jesus",
  "155 - Imploramos Teu Poder",
  "156 - A Ovelha Perdida",
  "157 - Cristo, em Breve, Vem!",
  "158 - Que Farás de Jesus Cristo?",
  "159 - Cantai, ó Peregrinos",
  "160 - Deus Nos Quis Salvar",
  "161 - Navegando Pra Terra Celeste",
  "162 - O Estandarte da Verdade",
  "163 - Cristo Morreu Por Mim",
  "164 - Paz Luz e Amor",
  "165 - A Armadura Cristã",
  "166 - Deixa Entrar o Rei da Glória",
  "167 - As Testemunhas de Jesus",
  "168 - Meus Irmãos, Nos Jubilemos",
  "169 - Oh! Jesus Me Ama",
  "170 - Ao Calvário de Horror",
  "171 - Um Pecador Remido",
  "172 - Ó Vem Te Entregar",
  "173 - Os Santos Louvam Ao Senhor",
  "174 - Glória, Aleluia, Gloria",
  "175 - Irmãos Amados",
  "176 - Sacerdotes do Senhor",
  "177 - Salvo Estou",
  "178 - Gloriosa Paz",
  "179 - Redentor Formoso",
  "180 - Em Cristo Fruímos a Paz",
  "181 - Vem, Celeste Redentor",
  "182 - Jesus no Getsêmane",
  "183 - Ressuscitou!",
  "184 - Meu Jesus! Meu Jesus!",
  "185 - Invocação e Louvor",
  "186 - De Valor em Valor",
  "187 - Mais Perto Meu Deus de Ti!",
  "188 - O Gozo do Céu",
  "189 - Glória ao Salvador",
  "190 - Cristo! Meu Cristo!",
  "191 - O Meu Jesus",
  "192 - Pelo Sangue",
  "193 - A Alma Abatida",
  "194 - Jesus Me Guiará",
  "195 - Benigno Salvador",
  "196 - Uma Flor Gloriosa",
  "197 - O Lar da Glória",
  "198 - Jesus o Bom Amigo",
  "199 - A Ceia do Senhor",
  "200 - O Bondoso Amigo",
  "201 - A Decisão",
  "202 - Lugar de Delícias",
  "203 - Deixai as Ilusões",
  "204 - O Peregrino da Terra",
  "205 - Graça, Graça",
  "206 - O Clarim nos Alerta",
  "207 - Jerusalém Divina",
  "208 - Vem a Cristo",
  "209 - A Voz do Bom Pastor",
  "210 - Fala, fala, Senhor",
  "211 - Vem a Deus",
  "212 - Os Guerreiros Se Preparam",
  "213 - Sobre a Terra Vou Andando",
  "214 - Desejamos ir Lá",
  "215 - Ver-nos-emos",
  "216 - Louvai a Deus",
  "217 - Ouve Sua Voz",
  "218 - Dá Teu Fardo a Jesus",
  "219 - O Amor do Criador",
  "220 - Ide Segar",
  "221 - Opera em Mim",
  "222 - Vem a Jesus, ó Perdido",
  "223 - Na Minh’Alma Reina a Paz",
  "224 - É o Tempo de Segar",
  "225 - Sê Valente",
  "226 - Cristo, Teu Santo Amor",
  "227 - Deus Amou de Tal Maneira",
  "228 - Este Mundo Não Compreende",
  "229 - Jesus, ó Meigo Salvador",
  "230 - Nós Vogamos Nesta Nau",
  "231 - Não Foi Com Ouro",
  "232 - Os Bem Aventurados",
  "233 - A Ceia Do Senhor",
  "234 - O Gozo Dos Santos",
  "235 - Já Sei, Já Sei",
  "236 - Já Nos Lavou",
  "237 - O Gozo de Estar Preparado",
  "238 - Ó Pecador Desalentado",
  "239 - Imploramos o Consolador",
  "240 - Oh Dia Alegre",
  "241 - Marchemos Sem Temor",
  "242 - Eu Confio Firmemente",
  "243 - Ao Abrir o Culto",
  "244 - Louvai a Jesus",
  "245 - Paz de Deus em Jesus Encontrei",
  "246 - O Descanso em Jesus",
  "247 - Deus Nos Guarde No Seu Amor",
  "248 - Hosana e Glória",
  "249 - Ó vem, Senhor, e Habita",
  "250 - Noiva de Jesus, Apronta-te",
  "251 - Ao Culto Não Faltar",
  "252 - Santo, Santo és Tu Senhor",
  "253 - Avante, ó Crentes",
  "254 - Mais Perto de Jesus",
  "255 - Meu Redentor",
  "256 - Abandona Este Mundo de Horror",
  "257 - O Perdão Sem Igual",
  "258 - Na Rocha Eterna Firmado",
  "259 - Creio eu na Bíblia",
  "260 - Avante com o Nosso Capitão",
  "261 - Alma Triste, Abatida",
  "262 - Senhor, Estás Comigo",
  "263 - Ao Fim do Culto",
  "264 - Ó Pai Celeste",
  "265 - Doce é Crer em Cristo",
  "266 - Resgatados Fomos",
  "267 - Jesus Minha Força",
  "268 - Confiante em Deus",
  "269 - Louvarei ao Meu Amado",
  "270 - Louvando ao Nosso Salvador",
  "271 - Na Mansão do Salvador",
  "272 - Quando Jesus Aparecer",
  "273 - Só a Ti Recorrerei",
  "274 - Jesus é a Luz do Mundo",
  "275 - Ó Acorda, Desperta!",
  "276 - Em Canaã Eu Entrarei",
  "277 - Salvo Estás? Limpo Estás?",
  "278 - Levar a Cruz",
  "279 - Ali Quero ir, e Tu?",
  "280 - Ó Jesus, Te Suplico",
  "281 - Vem Sem Tardar",
  "282 - Que Sangue Precioso",
  "283 - O Pastor e as Ovelhas",
  "284 - Bendito Cristo, Eis-me Aqui",
  "285 - Tu És o Meu Gozo",
  "286 - Não Tarda Vir Jesus!",
  "287 - Oh, Foi o Sangue",
  "288 - A Palavra da Cruz",
  "289 - Sob o Sangue Teu",
  "290 - Teu Espírito Vem Derramar",
  "291 - A Mensagem da Cruz",
  "292 - Qual o Preço do Perdão",
  "293 - Jesus no Calvário",
  "294 - Eu Vou Com Jesus",
  "295 - Novo Canto de Louvor",
  "296 - No Jardim",
  "297 - Abundância de Cristo",
  "298 - Avante, Servos de Jesus",
  "299 - Há um Canto Novo",
  "300 - Nossa Esperança",
  "301 - Vem Cear",
  "302 - Não Murmures; Canta",
  "303 - Precisamos de Jesus",
  "304 - A Face Adorada de Jesus",
  "305 - Campeões da luz",
  "306 - A Palavra de Deus é um Tesouro",
  "307 - Louvor ao Deus Trino",
  "308 - Só o Sangue de Jesus",
  "309 - Ao Findar do Dia",
  "310 - Avante Eu Vou",
  "311 - Jesus, Meu Salvador",
  "312 - A Vinda de Cristo",
  "313 - Louvor a Trindade",
  "314 - O pai bondoso",
  "315 - Oh! Amor Bendito",
  "316 - Em Busca de Sião",
  "317 - Jesus Vem Triunfante",
  "318 - Ao Lar Paternal",
  "319 - Ainda Há Lugar",
  "320 - Seguir a Cristo",
  "321 - Só em Jesus",
  "322 - As Santas Escrituras",
  "323 - Levantai Vossos Olhos",
  "324 - Jesus, o Melhor Amigo",
  "325 - A Luz do Céu Raiou",
  "326 - Oh! Meu Jesus",
  "327 - Teu Nome Precioso",
  "328 - O Pão da Vida",
  "329 - Jesus é Minha Paz",
  "330 - A Fé dos Santos",
  "331 - Ó Caro Salvador",
  "332 - Para o Céu eu vou",
  "333 - O Céu, Meu Lar",
  "334 - O Fim Vem, Cuidado!",
  "335 - Mui Perto Está o Dia",
  "336 - Oração de Elias",
  "337 - O Bom Jesus",
  "338 - Quero Jesus, Tua Luz",
  "339 - Jesus Ressuscitado",
  "340 - Um Povo Forte",
  "341 - A Aspiração da Alma",
  "342 - As Cordas do Coração",
  "343 - Abre o Coração",
  "344 - Um Amigo Entre os Lírios",
  "345 - Oh! Tenho Gozo",
  "346 - É Meu o Céu",
  "347 - Vem a Cristo",
  "348 - Longe de Jesus",
  "349 - Os Dons do Céu",
  "350 - A História da Cruz",
  "351 - A Felicidade da Salvação",
  "352 - Jesus, Nossa Esperança",
  "353 - Vem, ó Pródigo",
  "354 - O Cuidado da Alma",
  "355 - Fala do Amor de Cristo",
  "356 - Oração Dominical",
  "357 - O Fim das Lutas",
  "358 - Senhor, Manda Teu Poder",
  "359 - Vem a Mim, Pecador",
  "360 - A Preciosa Fonte",
  "361 - O Peregrino da Glória",
  "362 - O Espírito Diz: Vem!",
  "363 - Consagração",
  "364 - Oh, que Paz!",
  "365 - Confiança em Jesus",
  "366 - O Nascimento de Jesus",
  "367 - Espírito Consolador",
  "368 - Jesus, Tudo prá Mim",
  "369 - Sob as Asas de Deus",
  "370 - Grato a Ti",
  "371 - Breve Vem o Dia",
  "372 - Vencerá",
  "373 - Vem a Teu Salvador",
  "374 - Vida Abundante",
  "375 - A Igreja Universal",
  "376 - Vamos Todos Trabalhar",
  "377 - As Promessas Que Não Falham",
  "378 - As Pisadas do Mestre",
  "379 - Salvo de Graça",
  "380 - Abraão e Seu Sacrifício",
  "381 - O Cordeiro de Deus",
  "382 - Olhando Para o Calvário",
  "383 - O Sustento da Alma",
  "384 - Sinto Vida do Senhor",
  "385 - Amemos o Senhor",
  "386 - Vencidos os Combates",
  "387 - Derrama Teu Espírito",
  "388 - Canta, ó Crente",
  "389 - Lava-me ó Deus",
  "390 - Um Coração Bondoso",
  "391 - Jesus no Monte da Ascensão",
  "392 - Peregrinos Somos",
  "393 - Há um Amigo Mui Chegado",
  "394 - A Mão ao Arado!",
  "395 - Ide por Todo Mundo",
  "396 - Além do Nosso Entendimento",
  "397 - O Salvador me Achou",
  "398 - Perto do Meu Redentor",
  "399 - Terra de Jesus",
  "400 - Em Jesus",
  "401 - Jesus Voltará",
  "402 - Ao Gólgota",
  "403 - Gozo Real",
  "404 - Em Glória Virá",
  "405 - Queres Perdão",
  "406 - A Sombra do Meu Redentor",
  "407 - Ó Criador Bendito",
  "408 - Abre os Meus Olhos",
  "409 - Trabalhadores do Evangelho",
  "410 - Jesus Meu Rei Glorioso",
  "411 - Nós Somos Teus",
  "412 - Jesus Cristo, Bem Amado",
  "413 - Meu Pastor",
  "414 - Tem Compaixão do Pecador",
  "415 - Jesus Te Quer Curar",
  "416 - Quando o Povo Salvo Entrar",
  "417 - Bastante Para Mim",
  "418 - Sou Um Soldado",
  "419 - Vinde, Pecadores",
  "420 - O Que Buscas Ansioso?",
  "421 - Careço de Jesus",
  "422 - No Céu não Entra Pecado",
  "423 - De Ti Preciso Mais",
  "424 - Seu Precioso Sangue",
  "425 - Perdido Andei",
  "426 - União Dos Irmãos",
  "427 - Vai Orando",
  "428 - A estrela da Alva",
  "429 - Escuta o Evangelho",
  "430 - Evangelho da Salvação",
  "431 - Cristo Chama o Pecador",
  "432 - Consagrado ao Senhor",
  "433 - Sois Benvindos",
  "434 - A Teus Pés",
  "435 - Jesus Me Levantou",
  "436 - Crentes Cantai!",
  "437 - O Dom Celeste",
  "438 - Voltai-vos Para Mim",
  "439 - Aos Pés de Cristo Prostrados",
  "440 - Faze Já o seu Querer",
  "441 - A Chuva do Consolador",
  "442 - Breve Verei o Bom Jesus",
  "443 - Larga o Mundo!",
  "444 - Escuta, Pobre Pecador",
  "445 - Resgatado Com O Sangue de Cristo",
  "446 - Ó Vem Já!",
  "447 - Nascer de Novo",
  "448 - Crentes, Avançai",
  "449 - À Beira da Estrada",
  "450 - Sol da Justiça",
  "451 - Meu Jesus Vem",
  "452 - Seguirei a Cristo",
  "453 - Deus é o mesmo",
  "454 - Alegrai-vos, ó Remidos",
  "455 - O Povo de Deus na Terra",
  "456 - A Fonte Transbordante",
  "457 - O Festim de Glória",
  "458 - Guia Meus Passos",
  "459 - As Firmes Promessas",
  "460 - Dize-o a Cristo",
  "461 - Jesus Chorou Sobre Jerusalém",
  "462 - Glória ao Salvador",
  "463 - O Povo de Abraão",
  "464 - Plena Graça",
  "465 - Ele Sofreu Por mim",
  "466 - Que Maravilha",
  "467 - Sobre as Ondas do Mar",
  "468 - Cristo Está Chamando",
  "469 - Ao Estrugir a Trombeta",
  "470 - Batismo",
  "471 - Avançai Fiéis",
  "472 - Em Meu Lugar",
  "473 - Outro Bem Não Acharei",
  "474 - Paz, Doce Paz",
  "475 - Em Belém",
  "476 - O Cego de Jericó",
  "477 - Sede Fortes",
  "478 - Eis-me Jesus",
  "479 - Ao Raiar do Novo Ano",
  "480 - Fim do Ano",
  "481 - Cristo e Sua Humilhação",
  "482 - Comunhão",
  "483 - Ora Vem Jesus",
  "484 - Meus Pecados Levou",
  "485 - Andando Para o Céu",
  "486 - Vasos Transbordantes",
  "487 - Doxologia",
  "488 - O Áureo Dia",
  "489 - Chegai Para Adorar",
  "490 - Passando Está",
  "491 - Há Poder no Sangue de Jesus",
  "492 - Jesus Virá do Céu",
  "493 - Ao Pai Voltai",
  "494 - Jerusalém Celestial",
  "495 - Cristo à Porta Está",
  "496 - Jesus me Tirou da Lama",
  "497 - Meu Bom Salvador",
  "498 - Guia-me ó Salvador",
  "499 - A Santa Bíblia",
  "500 - Quero ver a Jesus Cristo",
  "501 - Vencendo Com o Bom Capitão",
  "502 - Ó Pastor Bendito",
  "503 - Vidas Consagradas ao Trabalho",
  "504 - Momento Solene",
  "505 - As Palavras de Jesus",
  "506 - Bíblia Sagrada",
  "507 - Jesus Salva",
  "508 - Sua Palavra Revelada",
  "509 - Ao Passar o Jordão",
  "510 - A Riqueza Divinal",
  "511 - Glorioso Deus",
  "512 - O Amor Inesgotável",
  "513 - Minha Alma Quer Ter",
  "514 - Em Glória Esplendente",
  "515 - Se Cristo Comigo Vai",
  "516 - Cristo Meu Vero Amigo",
  "517 - Cura Divina",
  "518 - Salva-Vidas",
  "519 - Achei Jesus, Meu Salvador",
  "520 - A Doce e Preciosa Voz",
  "521 - Vem o Passo Dar!",
  "522 - Rei da Glória",
  "523 - Cristo, a Fonte Escondida",
  "524 - Cristo Pensa em Mim",
  "525 - Vencendo Vem Jesus",
  "526 - Grandioso És Tu",
  "527 - Dominador É Deus",
  "528 - Eu Te Amo, Ó Deus",
  "529 - Em Sua Graça",
  "530 - Vivifica a Tua Igreja",
  "531 - Nome Precioso",
  "532 - Santo Nome",
  "533 - Honras Sejam ao Cordeiro",
  "534 - Cristo É Real Pra Mim",
  "535 - Tu És Fiel Senhor",
  "536 - Amigo Sem Igual",
  "537 - Sempre Comigo",
  "538 - Tu, Senhor, És Nosso Amigo",
  "539 - Ao Pensar na Dor Crucial",
  "540 - Ao Ver a Cruz",
  "541 - Calvário, Revelação de Amor",
  "542 - História de Cristo",
  "543 - Cristo, Meu redentor",
  "544 - Creio, Senhor",
  "545 - Porque Ele Vive",
  "546 - Manhã da Ressurreição",
  "547 - O Rei Está Voltando",
  "548 - Breve Jesus Há de Vir",
  "549 - Ora Vem, Senhor Jesus",
  "550 - Breve Ele Volta",
  "551 - O Santo Espírito",
  "552 - Quando para o Céu Nós Formos",
  "553 - Oh! Pai, o Santo Espírito",
  "554 - O Evangelho",
  "555 - O Redentor",
  "556 - Lê a Bíblia",
  "557 - A Palavra da Vida",
  "558 - Daí-me a Bíblia",
  "559 - Bíblia Sagrada",
  "560 - Tenho Paz em Meu Ser",
  "561 - Que Bênção!",
  "562 - Autor da Vida",
  "563 - Sempre Feliz",
  "564 - Conta as Bênçãos",
  "565 - Tu És Meu",
  "566 - Paz Perfeita, Sim, Busquei",
  "567 - Sou Feliz",
  "568 - Manso e Suave",
  "569 - Morri na cruz por Ti",
  "570 - A Última Hora",
  "571 - Rende o Coração",
  "572 - A Porta Sou",
  "573 - A Graça de Nosso Senhor",
  "574 - Ó Pai Bondoso",
  "575 - Espero em Ti",
  "576 - Assim como estou",
  "577 - Em Fervente Oração",
  "578 - Sossegai!",
  "579 - Porque te Afliges?",
  "580 - Salmo 121",
  "581 - Castelo Forte",
  "582 - A Barca da Vida",
  "583 - Sê Tu Meu Guia",
  "584 - O Piloto",
  "585 - Jesus me Satisfaz",
  "586 - Gozo e Vida Tenho",
  "587 - Neste Lenho me Glorio",
  "588 - Sou Mui Feliz",
  "589 - Quádruplo Amém",
  "590 - Contentamento",
  "591 - Pura, Sim, Mais Pura",
  "592 - O Lugar de Bênção e Paz",
  "593 - Estou Seguro",
  "594 - Fé Persistente",
  "595 - Somente a Ti!",
  "596 - Gratidão",
  "597 - Graça Dou",
  "598 - Riquezas do Céu",
  "599 - Herdeiro do Reino",
  "600 - Mãos ao Trabalho",
  "601 - A Seara está Madura",
  "602 - Juntos Trabalhamos",
  "603 - Método de Deus",
  "604 - Senhor, os Mensageiros Teus",
  "605 - Quero te Servir",
  "606 - Triunfo",
  "607 - Luz após Trevas",
  "608 - Se em Teu Caminho",
  "609 - Vitória Deus Dará a Mim",
  "610 - Fé É a Vitória",
  "611 - Cristo, Comandante",
  "612 - Ó Pai Eterno",
  "613 - Vitória Final",
  "614 - Terra Feliz",
  "615 - Vou Rumo ao Meu Lar",
  "616 - Quanto Almejo!",
  "617 - Quanto Anelo",
  "618 - É Nosso o Lar",
  "619 - Meu Lar, Jerusalém",
  "620 - Na Jornada Para Jerusalém",
  "621 - Juntos, no Céu",
  "622 - Tão Grato me é Lembrar",
  "623 - Oh, Sim, Bem Sei",
  "624 - Anseio um Lugar de Amor",
  "625 - Glória Indizível",
  "626 - Tríplice Amém",
  "627 - Finda-se Minha Prisão",
  "628 - Além do céu Azul",
  "629 - Conversaremos Ali no Céu",
  "630 - Não Há Separação na Glória",
  "631 - Neste Lugar",
  "632 - Mais um Templo",
  "633 - Meu Brasil",
  "634 - Oração pela Pátria",
  "635 - Eis o Brasil em Tuas Mãos",
  "636 - Por nossa Pátria Oramos",
  "637 - Hino à Bandeira Nacional",
  "638 - Hino Nacional Brasileiro",
  "639 - Hino da Independência",
  "640 - Hino da Proclamação da República do Brasil",
];